version: '3'

services:
  distroless:
    image: golang-distroless
    build:
      context: ./
      dockerfile: ./golang-distroless/Dockerfile

  alpine:
    image: golang-alpine
    build:
      context: ./
      dockerfile: ./golang-alpine/Dockerfile
